version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: SnowSite.Server/Dockerfile
    ports:
      - "5020:80"
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: snowsite.client/Dockerfile
    ports:
      - "8080:80"

  tests:
    build:
      context: .
      dockerfile: ApiTests/Dockerfile
    depends_on:
      - backend
      - frontend