name: Deploy SnowSite

on:
  push:
    branches:
      - master # Разворачивание при обновлении ветки main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Чекаут кода
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Установка Node.js для клиентской части
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Сборка клиентской части
      - name: Build SnowSite.client
        run: |
          cd SnowSite.client
          npm install
          npm run build

      # 4. Установка .NET для Web API
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # 5. Сборка и публикация Web API
      - name: Build and Publish SnowSite.Server
        run: |
          cd SnowSite.Server
          dotnet publish -c Release -o ./publish

      # 6. Деплой на сервер через SSH с паролем
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            # Остановка служб
            sudo systemctl stop snowsite-client
            sudo systemctl stop snowsite-api

            # Обновление клиентской части
            rm -rf /var/www/snowsite/*
            cp -r ~/repo/SnowSite.client/dist/* /var/www/snowsite/
            sudo chown -R $USER:$USER /var/www/snowsite

            # Обновление Web API
            rm -rf /var/www/snowsite-api/*
            cp -r ~/repo/SnowSite.Server/publish/* /var/www/snowsite-api/
            sudo chown -R $USER:$USER /var/www/snowsite-api

            # Перезапуск служб
            sudo systemctl start snowsite-client
            sudo systemctl start snowsite-api

      # 7. Очистка временных файлов (опционально)
      - name: Cleanup
        run: |
          rm -rf SnowSite.client/dist
          rm -rf SnowSite.Server/publish